version: '3.5'
services:
  vue-ui-admin:
    image: lucaspintos909/admin-frontend
    ports:
      - "8081:80"
  vue-ui-docente:
    image: lucaspintos909/docente-frontend
    ports:
      - "8082:80"
  vue-ui-alumno:
    image: lucaspintos909/alumno-frontend
    ports:
      - "8083:80"